import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "../utils/api";
import { useState } from "react";

import Navbar from "../components/Navbar";

const Home: NextPage = () => {
  const session = useSession();
  return (
    <>
      <Head>
        <title>Cobra</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex w-full flex-1 flex-col items-center justify-center px-20 text-center">
        <h1 className="text-6xl font-bold">Home</h1>
        {session.data?.user ? (
          <>
            <p>You are signed in</p>
            <PostForm />
            <button onClick={() => signOut()}>Sign out</button>
          </>
        ) : (
          <>
            <p>You are not signed in</p>
            <button onClick={() => signIn()}>Sign in</button>
          </>
        )}
      </main>
    </>
  );
};

export default Home;

const PostForm: React.FC = () => {
  const [title, setTitle] = useState<string>("");
  const [body, setBody] = useState<string>("");
  const mutation = api.post.create.useMutation();
  const session = useSession();

  const handleSubmit = (e) => {
    e.preventDefault();
    if (session.data?.user) {
      mutation.mutate({ title, content: body, authorId: session.data.user.id });
    }
    e.target.reset();
  };

  return (
    <form onSubmit={handleSubmit} className="flex flex-col items-center">
      <label htmlFor="title">Title</label>
      <input
        className="mb-2 border"
        type="text"
        value={title}
        onChange={(e) => setTitle(e.target.value)}
      />
      <label htmlFor="body">Body</label>
      <input
        className="mb-2 border"
        type="text"
        value={body}
        onChange={(e) => setBody(e.target.value)}
      />
      <button type="submit">Submit</button>
    </form>
  );
};
